services:
  - type: web
    name: competitive-programming-assistant
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_main.py"
    autoDeploy: true
    envVars:
      - key: AUTH_TOKEN
        sync: false
      - key: CLIST_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MY_NUMBER
        sync: false
      - key: DEFAULT_HANDLE
        sync: false
